frontend: define the Rectangle type
Why?
because when we build the frontend we
receive this error:
```
src/components/pong/BoardGame.tsx(4,55): error TS7006: Parameter 'rectangle' implicitly has an 'any' type.
```