This is a combination of 3 commits.
This is a combination of 6 commits.

Start of fetching myfriends feature

friend.module:
- added forwardRef to avoid circular
dependency error between mutually
importing modules.

friend.service:
- creation of  getAllFriendsByUserId()
method to retrieve all friends of a given
user

user.controller:
- renaming the endpoint
'GET api/user/user/me' to 'GET
api/user/getmyinfo'

- shifting logic from
GET api/user/user/getmyinfo endpoint to
user.service.getMyInfo() method

- creation of the 'GET api/user/getmyfriends'
endpoint in charge of retrieving the
user's friends list using the
userService.getMyFriends() method

user.module:
- added forwardRef to avoid
circular dependency error between mutually
importing modules

- provider aggregation

user.service:
- creation of getMyInfo()
method which is used by the endpoint 'GET
api/user/getmyinfo'

- creation of the
getMyFriends() method used by the 'GET
api/user/getmyfriends' endpoint

Main.Profile:
- update of the endpoint to
be fetched to be consistent with the
rename done in the backend

Solving a dependency problem

Error: 'Nest can't resolve dependencies of
the FriendService (FriendRepository, ?)'

Dependency error correction

Make format

Fetch friends every 1500 msec

Filter user's infos

Fetch friends working

quick comment fix

Change 'history button' for 'Add friend button'

Just the frontend. This button doesn't really work.

Separate 'friends' from 'friend requests'.

Creation of status attribute in user entity

Moving the logout logic from the
user.controller file to user.service.

Inside user.service we created the
'changeStatusOnLine' and
'changeStatusPlaying' methods in charge of
modifying the 'state' attribute of the
user class.

When a user logs in, the
'changeStatusOnLine' method is called.

When a user logs out, the 'logout' method
is called.

In the same way, when a user starts to
play, the 'changeStatusOnLine' method
should be called.

Modification of 'Dummy data' in order to
attribute the variable 'status' to the
fake users during their creation.

Add status display in frontend

Button 'Add new friends' now fetch infos

Work in progress...

Requests now send friends and pendings

npm uninstall axios --save