Friends feature (#88)
Now you can: 

- delete friends
- accept friend requests sent by another
user    
- delete requests that you have sent
yourself
- add new friends by choosing them from
a list of all users who are not our friends 

To test it: 

- make clean-database
- make    
- login with 42
- http://localhost:8080/api/ (create
dummy data)    
- go to profile page    
- accept, delete, add friends 

You should have a pending friend request 
from another user along with other things


Commits history:

friend.module:
- added forwardRef to avoid circular
dependency error between mutually
importing modules.

friend.service:
- creation of  getAllFriendsByUserId()
method to retrieve all friends of a given
user

- shifting logic from
GET api/user/user/getmyinfo endpoint to
user.service.getMyInfo() method

- creation of the 'GET api/user/getmyfriends'
endpoint in charge of retrieving the
user's friends list using the
userService.getMyFriends() method

user.module:
- added forwardRef to avoid
circular dependency error between mutually
importing modules

- provider aggregation

user.service:
- creation of getMyInfo()
method which is used by the endpoint 'GET
api/user/getmyinfo'

- creation of the
getMyFriends() method used by the 'GET
api/user/getmyfriends' endpoint

Main.Profile:
- update of the endpoint to
be fetched to be consistent with the
rename done in the backend

Solving a dependency problem

Error: 'Nest can't resolve dependencies of
the FriendService (FriendRepository, ?)'

Dependency error correction

Make format

Fetch friends every 1500 msec

Filter user's infos

Fetch friends working

quick comment fix

Change 'history button' for 'Add friend button'

Just the frontend. This button doesn't really work.

Separate 'friends' from 'friend requests'.

Creation of status attribute in user entity

Moving the logout logic from the
user.controller file to user.service.

Inside user.service we created the
'changeStatusOnLine' and
'changeStatusPlaying' methods in charge of
modifying the 'state' attribute of the
user class.

When a user logs in, the
'changeStatusOnLine' method is called.

When a user logs out, the 'logout' method
is called.

In the same way, when a user starts to
play, the 'changeStatusOnLine' method
should be called.

Modification of 'Dummy data' in order to
attribute the variable 'status' to the
fake users during their creation.

Add status display in frontend

Button 'Add new friends' now fetch infos

Work in progress...

Requests now send friends and pendings

npm uninstall axios --save

* Frontend show friend list

Frontend receives and correctly
displays the list of friends and
friend requests

* Icons based on who created the friend request

* Accept and delete requests

Accept friendship request works
Delete friendship works

* New friends can now be added

* Friend requests can now be rejected

* add not friend to dummy data

* Add friends functionality working

* Rename variables to improve readability

* Delete unused element

* Problems during compilation solved

* R front fetch myfriends custom link (#89)

* CustomLink.tsx created

* delete CustomLink from Friend.tsx

---------

Co-authored-by: Robin Burri <robin@Robins-MacBook-Air.local>

* Simplify and delete span

Simplify, no need to return an empty div if successfullyDone.
    span with title is useless (I don't see it anywhere on the page)

Co-authored-by: Robin Burri <robinburri@tutanota.com>

* Simplify and delete span

Simplify, no need to return an empty div if successfullyDone.
    span with title is useless (I don't see it anywhere on the page)

Co-authored-by: Robin Burri <robinburri@tutanota.com>

* format

Co-authored-by: Theo Grivel <grivel.theo@protonmail.com>