remove import React
Why?
because when we build the frontend we
receive this error:
```
src/components/profile/ClickableIcon.tsx(1,1): error TS6133: 'React' is declared but its value is never read.
src/components/profile/Friend.tsx(1,1): error TS6133: 'React' is declared but its value is never read.
src/components/profile/StatisticElement.tsx(1,1): error TS6133: 'React' is declared but its value is never read.
src/components/profile/UserInformation.tsx(1,1): error TS6133: 'React' is declared but its value is never read.
```

command used:
sed -i \
':a;N;$!ba;s/import React from .react.\n//g' \
$(find frontend/src/components/profile -type f)

source:
how replace newline with sed
https://stackoverflow.com/questions/1251999/how-can-i-replace-each-newline-n-with-a-space-using-sed